name: Analisis de Seguridad con Bandit

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependencias necesarias
      run: |
        pip install bandit
        pip install requests  # 👈 Añadido

    - name: Ejecutar escaneo de vulnerabilidades
      run: bandit -r . -ll
